// packages/templates/astro-vue-template/src/components/Card.vue
<script setup lang="ts">

interface Props {
  title: string;
  src: string;
  alt?: string;
  width:number
  height:number
}

const { title, src, alt, height, width } = defineProps<Props>();

</script>
---

<template>
  
  <div class="grid">
  <header>
    <img 
    :src="src" 
    :height="height" 
    :width="width" 
    :alt="alt" 
    />
  </header>
  <div class="py-2 px-4">
    <div class="text-xl">{{title}}</div>
  </div>
  <footer class="">
    <slot />
  </footer>
</div>

</template>

// templates/preact-template/src/components/Card.tsx
import type { FunctionalComponent, JSX } from "preact";


interface Props {
  title: string;
  src: string;
  alt?: string;
  footer: JSX.Element
}


const  Card:FunctionalComponent<Props> = (props) => {
  const { title, src, alt, children, footer } = props;


  return <div class="grid">
    <header>
      <img src={src} alt={alt} />
      <div class="text-xl">{title}</div>
    </header>
    <div class="py-2 px-4">
      {children}
    </div>
    <footer class="">
      {footer}
    </footer>
  </div>

}

export { Card }
